# Code Generated by ZenTest v. 3.11.1

require 'test/unit' unless defined? $ZENTEST and $ZENTEST

$:.unshift File.dirname(__FILE__) + "/../lib" 
require 'relisp'


module TestRelisp
  class TestProxy < Test::Unit::TestCase
    def setup
      @emacs = Relisp::ElispSlave.new
    end
  
    def test_class_from_elisp
      test_buffer_name = "*relisp-test-buffer*"
      buffer = @emacs.elisp_eval( "(create-file-buffer \"#{test_buffer_name}\") " )
      assert_kind_of Relisp::Buffer, buffer
      buffer_names = @emacs.elisp_eval( '(buffer-list)' ).to_list.map { |buffer| buffer.name } 
      assert buffer_names.include?(test_buffer_name)
    end

    # This is really tested in all of the other classes.
    def test_initialize
      new_buffer = Relisp::Buffer.new("new-buffer")
      assert_kind_of Relisp::Buffer, new_buffer
      assert_equal "new-buffer", new_buffer.name
    end

    def test_to_elisp
      test_buffer_name = "*relisp-test-buffer*"
      buffer = @emacs.elisp_eval( "(create-file-buffer \"#{test_buffer_name}\") " )
      assert_equal :buffer, @emacs.elisp_eval("(type-of #{buffer.to_elisp})")
    end
  end


  class TestBuffer < Test::Unit::TestCase
    def setup
      @emacs = Relisp::ElispSlave.new
    end
  
    def test_class_from_elisp
      test_buffer_name = "*relisp-test-buffer*"
      buffer = @emacs.elisp_eval( "(create-file-buffer \"#{test_buffer_name}\") " )
      assert_kind_of Relisp::Buffer, buffer
      buffer_names = @emacs.elisp_eval( '(buffer-list)' ).to_list.map { |buffer| buffer.name } 
      assert buffer_names.include?(test_buffer_name)
    end

    def test_initialize
      new_buffer = Relisp::Buffer.new("new-buffer")
      assert_kind_of Relisp::Buffer, new_buffer
      assert_equal "new-buffer", new_buffer.name
      found_buffer = @emacs.get_buffer(new_buffer.name)
      assert_kind_of Relisp::Buffer, found_buffer
    end

    def test_to_elisp
      test_buffer_name = "*relisp-test-buffer*"
      buffer = @emacs.elisp_eval( "(create-file-buffer \"#{test_buffer_name}\") " )
      assert_equal :buffer, @emacs.elisp_eval("(type-of #{buffer.to_elisp})")
    end

    def test_set
      b1_name = "*relisp-test-buffer1*"
      b2_name = "*relisp-test-buffer2*"
      b1 = Relisp::Buffer.new b1_name
      b2 = Relisp::Buffer.new b2_name
      
      b1.set
      assert_equal b1_name, @emacs.buffer_name
      b2.set
      assert_equal b2_name, @emacs.buffer_name
    end

    def test_name
      test_buffer_name = "*relisp-test-buffer*"
      buffer = @emacs.elisp_eval( "(create-file-buffer \"#{test_buffer_name}\") " )
      assert_equal test_buffer_name, buffer.name
    end

    def test_rename
      b = Relisp::Buffer.new "*relisp-test-buffer*"
      assert_equal b.name, "*relisp-test-buffer*"
      b.insert "this text should stay here"
      text = b.to_s
      b.rename "*same-relisp-buffer*"
      assert_equal b.name, "*same-relisp-buffer*"
      assert_equal text, b.to_s
    end

    def test_filename
      
    end


  end

  class TestMarker < Test::Unit::TestCase
    def setup
      @emacs = Relisp::ElispSlave.new
    end

    def test_class_from_elisp
      assert_kind_of Relisp::Marker, @emacs.point_marker
      assert @emacs.elisp_eval( "(equal #{@emacs.point_marker.to_elisp} (point-marker))" )
      assert_kind_of Relisp::Marker, Relisp::Marker.new
    end

    def test_to_elisp
      assert_equal :marker, @emacs.elisp_eval( "(type-of #{@emacs.point_marker.to_elisp})" )
    end
  end

  class TestWindow < Test::Unit::TestCase
    def setup
      @emacs = Relisp::ElispSlave.new
    end

    def test_class_from_elisp
      assert_kind_of Relisp::Window, @emacs.selected_window
    end
  end

  class TestFrame < Test::Unit::TestCase
    def setup
      @emacs = Relisp::ElispSlave.new
    end

    def test_class_from_elisp
      assert_kind_of Relisp::Frame, @emacs.selected_frame
    end
    
    def test_initialize
      new_frame = Relisp::Frame.new
      assert_kind_of Relisp::Frame, new_frame
      assert_equal :frame,  @emacs.elisp_eval( "(type-of #{new_frame.to_elisp})")
      new_frame = Relisp::Frame.new({:width => 30, :height => 20})
      assert_kind_of Relisp::Frame, new_frame
      assert_equal :frame,  @emacs.elisp_eval( "(type-of #{new_frame.to_elisp})")
    end
  end

  class TestWindowConfiguration < Test::Unit::TestCase
    def setup
      @emacs = Relisp::ElispSlave.new
    end

    def test_class_from_elisp
      assert_kind_of Relisp::WindowConfiguration, @emacs.current_window_configuration
    end
  end

  class TestProcess < Test::Unit::TestCase
    def setup
      @emacs = Relisp::ElispSlave.new
    end
    
    def test_class_from_elisp
      assert_kind_of Relisp::Process, @emacs.start_process("test", "test", "ls")
    end

  end

  class TestOverlay < Test::Unit::TestCase
    def setup
      @emacs = Relisp::ElispSlave.new
    end
    
    def test_class_from_elisp
      @emacs.insert("sometext")
      assert_kind_of Relisp::Overlay,  @emacs.elisp_eval( "(make-overlay 1 3)")
    end

    def test_initialize
      @emacs.insert("sometext")
      new_overlay = Relisp::Overlay.new(1, 3)
      assert_kind_of Relisp::Overlay, new_overlay
      assert_equal :overlay,  @emacs.elisp_eval( "(type-of #{new_overlay.to_elisp})")
    end

  end

end

