#!/usr/bin/env ruby

$:.unshift File.join(File.dirname(__FILE__), "../../lib") 

require 'relisp'

emacs = Relisp::ElispSlave.new
# emacs.debugging do

# basic functionality
puts "elisp_exec: "
puts emacs.elisp_exec("(+ 1 2)").to_s
puts "elisp_eval: "
puts emacs.elisp_eval("(+ 1 2)").to_s

puts (emacs.elisp_eval '(concat "two " "words")')
puts emacs.concat "two ", "words"

emacs.set(:a, 3)
puts emacs.symbol_value(:a)
puts emacs.a
emacs.a= 5
puts emacs.a

# variable persistence between calls
emacs.elisp_eval "(setq new-var 23)"
puts emacs.elisp_eval "(+ 1 new-var)"

puts emacs.elisp_eval '(ruby-eval "1 + 3")'

# wrappers around elisp editing data types
buffer = Relisp::Buffer.new("ruby-created-buffer")
puts buffer.to_s
puts buffer.name
puts emacs.create_file_buffer("blah.txt").class
#end
