#!/usr/bin/env ruby

local_vars = binding

def ruby_method
  puts "(+ 1 3)"
#  puts 'relisp-ruby-return'
  puts $over_string

  sss = String.new
  until gets.strip == $terminal_string
    sss << $_
  end
  puts sss
end

begin
  loop do
    $terminal_string = gets.strip
    $over_string     = gets.strip
    
    code = String.new
    until gets.strip == $terminal_string 
      code << $_
    end
    
    puts (eval code, local_vars).to_s
    puts $terminal_string
  end
rescue => dag_yo
  puts "Ruby error: " + dag_yo
  puts terminal_string
end


