#!/usr/bin/env ruby

def ruby_method
  puts "(+ 1 3)"
  puts RELISP.over_string

  2.times { gets }

   elisp_return_value = String.new
   until gets.strip == RELISP.terminal_string
     elisp_return_value << $_
   end

  return elisp_return_value.to_i + 3
end

module RELISP
  def self.terminal_string
    @terminal_string
  end

  def self.over_string
    @over_string
  end

  def self.start_controller
    local_vars = self.instance_eval {binding}
    
    begin
      loop do
        @terminal_string = gets.strip
        @over_string     = gets.strip
        
        code = String.new
        until gets.strip == @terminal_string 
          code << $_
        end
        
        puts (eval code, local_vars).to_s
        puts @terminal_string
      end
    rescue => dag_yo
      puts "Ruby error: " + dag_yo
      puts @terminal_string
    end
  end 
end

RELISP.start_controller
